### ISSUE TITLE
install no longer works

### ISSUE THREAD

**Issue by kohlhase** [slatex/stexls#14]
after I uninstall stexls and it tries to install, I get 
```
ModuleNotFoundError: No module named 'packaging'
```

**Comment by kohlhase** [comment]
ah, the error is longer: 
```
> python3 -m pip install "git+https://github.com/slatex/stexls.git"
> python3 -m stexls --version
Error: Command failed: python3 -m stexls --version
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/stexls/__main__.py", line 13, in <module>
    from .linter.cli import linter
  File "/usr/local/lib/python3.9/site-packages/stexls/linter/cli.py", line 7, in <module>
    from .linter import Linter
  File "/usr/local/lib/python3.9/site-packages/stexls/linter/linter.py", line 7, in <module>
    from ..stex.compiler import Compiler, StexObject
  File "/usr/local/lib/python3.9/site-packages/stexls/stex/compiler.py", line 28, in <module>
    from packaging.version import parse as parse_version
ModuleNotFoundError: No module named 'packaging'


```

**Comment by kohlhase** [comment]
Ok, I manually installed `packaging` with pip3, and that helped.

**Comment by Mari6814** [comment]
I added it to the setup files...
I thought it was from the standard library.
For now installing it by hand works as well.

**Comment by kohlhase** [comment]
thanks.
